/**
 * MML API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QueryFormatting } from './query-formatting';
import { SQLNamespace } from './sql-namespace';

export interface BodyValidateMetricaMetricaValidatePost {
  ns?: SQLNamespace;
  qf?: QueryFormatting;
}
