/**
 * MML API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SQLNamespace } from "./sql-namespace";
import { QueryFormating } from "./query-formating";

export interface BodyValidateMetricaMetricaValidatePost {
  ns?: SQLNamespace;
  qf?: QueryFormating;
}
