/**
 * MML API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Column {
  name: string;
  type: string;
  nullable: boolean;
  default?: any | null;
  comment?: string;
  properties?: Record<string, string[]>;
}
