/**
 * MML API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * SQLAlchemy database connection configuration.
 */
export interface DBconnectionInput {
  /**
   * dialect+driver://username:password@host:port/database?p1=v1&p2=v2
   */
  url?: string;
  connect_args?: object;
  engine_kwargs?: object;
}
