/**
 * MML API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface MetricaApi {
  sql: string;
  base_table: string;
  metrics: Set<string>;
  parameters: Set<string>;
}
