/**
 * MML API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Add a metric.
 */
export interface MetricaResponce {
  sql: string;
  base_table: string;
  metrics: Array<string>;
  parameters: Array<string>;
}
