/**
 * MML API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface QueryFormating {
  dialect?: string;
  normalize?: boolean;
  normalize_functions?: QueryFormating.NormalizeFunctionsEnum;
  max_text_width?: number;
}
export namespace QueryFormating {
  export type NormalizeFunctionsEnum = "upper" | "lower";
  export const NormalizeFunctionsEnum = {
    Upper: "upper" as NormalizeFunctionsEnum,
    Lower: "lower" as NormalizeFunctionsEnum,
  };
}
