/**
 * MML API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface QueryFormatting {
  dialect?: string;
  normalize?: boolean;
  normalize_functions?: QueryFormatting.NormalizeFunctionsEnum;
  max_text_width?: number;
}
export namespace QueryFormatting {
  export const NormalizeFunctionsEnum = {
    Upper: 'upper',
    Lower: 'lower',
  } as const;
  export type NormalizeFunctionsEnum =
    (typeof NormalizeFunctionsEnum)[keyof typeof NormalizeFunctionsEnum];
}
