/**
 * MML API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SQLNamespace } from './sql-namespace';
import { QueryFormating } from './query-formating';
import { DBconnectionInput } from './d-bconnection-input';

export interface SettingsInput {
  log_level?: SettingsInput.LogLevelEnum;
  component_log_levels?: { [key: string]: string };
  case_sensitive?: boolean;
  schema_config?: string;
  env?: SettingsInput.EnvEnum;
  namespace?: SQLNamespace;
  query_formating?: QueryFormating;
  db_conn?: DBconnectionInput;
}
export namespace SettingsInput {
  export type LogLevelEnum =
    | 'CRITICAL'
    | 'ERROR'
    | 'WARNING'
    | 'INFO'
    | 'DEBUG'
    | 'NOTSET';
  export const LogLevelEnum = {
    Critical: 'CRITICAL' as LogLevelEnum,
    Error: 'ERROR' as LogLevelEnum,
    Warning: 'WARNING' as LogLevelEnum,
    Info: 'INFO' as LogLevelEnum,
    Debug: 'DEBUG' as LogLevelEnum,
    Notset: 'NOTSET' as LogLevelEnum,
  };
  export type EnvEnum = 'development' | 'testing' | 'default' | 'production';
  export const EnvEnum = {
    Development: 'development' as EnvEnum,
    Testing: 'testing' as EnvEnum,
    Default: 'default' as EnvEnum,
    Production: 'production' as EnvEnum,
  };
}
