/**
 * MML API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Column } from './column';

export interface TableApi {
  name: string;
  comment?: string;
  columns: Record<string, Column>;
  properties?: Record<string, string[]>;
}
